export {default as AppPage} from '@pages/app/AppPage.tsx'
export {default as LoginPage} from '@pages/login/LoginPage.tsx'
export {default as RegisterPage} from '@pages/register/RegisterPage.tsx'
export {default as NotFoundPage} from '@pages/not-found/NotFoundPage.tsx'
export {default as VerifyAccountPage} from '@pages/verify-account/VerifyAccountPage.tsx'
