server:
  port: 9000
  servlet:
    context-path: /api
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/memo
    password: root@123
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: myominhtoo2003@gmail.com
    password: vmdqljrqbilexqpz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    throw-exception-if-no-handler-found: true
  task:
    scheduling:
      pool:
        size: 5
jwt:
  issuer: MMHTOO@DEV
  age: 1 # one month
app:
  verificationUrl: http://localhost:9000/api/accounts/verify
  redirectUrlAfterVerified: http://localhost:3000
  clientUrl : http://localhost:3000
